name       : python-vdf
version    : '3.4'
release    : 4
source     :
    - https://github.com/ValvePython/vdf/archive/refs/tags/v3.4.tar.gz : c9fb42b6de9daf475cd229377d0c32d6e87c0f21e874a35e0e679eb201723a67
homepage   : https://github.com/ValvePython/vdf
license    : MIT
component  : programming.python
summary    : Python module for working with Valve's text and binary KeyValue format
description: |
    Python module for (de)serialization to and from VDF that works just like json
build      : |
    %python3_setup
install    : |
    %python3_install
